#+TITLE:
#+STARTUP: content indent

* Clases Regulares semanales o quincenales

Clases grupales pero con seguimiento individual por lo que *se puede comenzar en cualquier momento*.

Explorá el diseño y conceptos para crear piezas únicas que trascienden lo convencional. Aprendé a transformar materiales en objetos que cuentan historias, expresan emociones y reflejan tu visión artística.

Dirigido tanto a quienes quieren iniciarse en el mundo de la joyería como a artistas o diseñadores que buscan ampliar sus posibilidades creativas.
+ Técnicas de fabricación y experimentación con materiales.
+ Desarrollo de lenguaje artístico y diseño de colecciones.

¡No se necesita experiencia!
Grupos reducidos para un seguimiento personalizado.

=FOTOS=

*HORARIOS*
+ Miércoles de 14 a 16 hs.
+ Jueves de 10 a 12 hs.
+ Jueves de 17 a 19 hs.
+ Sábados quincenales de 9 a 13 hs.


* Experiencias "Un día de taller"

Sumate a la experiencia de diseñar y hacer con tus propias manos mientras disfrutás de un momento único.

Experimentá un día de taller para crear tu propia pieza de joyería. No necesitás ningún tipo de conocimiento especial, cualquiera puede sumarse.

** Un día, un anillo

_Disfrutá de esta experiencia en un ambiente de creatividad y llevate tu propio anillo._

En este seminario vas a de aprender a hacer tu propio anillo en alpaca, cobre o bronce.

Vas a descubrir las posibilidades del metal:
+ Cortar con sierra, tijera o cizalla.
+ Texturar con martillos o laminadora.
+ Dar forma al anillo con mandril, pinzas y masa.
+ Buscar la terminación deseada con limas y lijas.
+ Pátinas.

TODO INCLUIDO.

** Un día, un brazalete.

_Un momento para crear, conectar y llevarte tu brazalete._

En este seminario vamos a experimentar con texturas, formas y pátinas del metal para hacer tu propio diseño mientras compartís un momento diferente.

Son grupos muy reducidos por lo que el seguimiento es individual. NO se necesita experiencia, ¡sólo ganas!

Se incluyen los materiales para explorar y después hacer tu brazalete en cobre, bronce o alpaca. También todas las herramientas necesarias. TODO INCLUIDO.
** Experiencias en cera

_¡Despertá tu creatividad y lleva tus ideas a la realidad con esta técnica milenaria!_

En este seminario vas a aprender a hacer una pieza eligiendo o combinando opciones de la técnica de cera perdida. La pieza -que puede ser colgante, aros o anillo- queda lista para fundición.

Vamos a ver y explorar:
+ Técnicas de modelado con ceras blandas.
+ Experimentación con ceras duras.
+ Orgánicos, textiles.
+ Proceso completo listo para la fundición en metal.

Materiales y herramientas incluidos. NO incluye los costos de fundición (se calculan al finalizar el taller y decidís en qué metal fundirlo).

Grupos reducidos para atención personalizada. No necesitás experiencia.


* Seminarios Intensivos

Regularmente se ofrecen seminarios intensivos sobre diferentes técnicas y materiales.


** Fundición con inclusión de piedras/cubics

_Ideal para quienes buscan explorar nuevas técnicas de joyería y diseño, o para quienes quieren perfeccionar sus habilidades en la creación de piezas personalizadas._

Curso práctico y creativo donde aprenderás a trabajar con modelado en cera, diseñando piezas que incorporan cubics o piedras directamente en el proceso.

Al finalizar tus modelos, los enviaremos a fundición.

** Biomateriales
_Vamos a conocer qué son los biomateriales y cómo podemos fabricarlos desde casa._

Este seminario busca acercar conceptos de sustentabilidad y desarrollo de nuevos materiales.

Veremos fórmulas básicas que haremos en clase para que puedas ver el proceso y experimentar. Realizaremos opciones para piezas de joyería/arte.

Compartiré archivo con fórmulas, materiales, páginas que brindan información, links a referentes, etc.

** Laca japonesa
_Ideal para quienes buscan introducirse en una técnica milenaria con potencial artístico y contemporáneo._

Aprendé las bases del arte tradicional japonés de la laca cashew, explorando sus aplicaciones en joyería, diseño y arte contemporáneo:
+ Historia y tipos de laca.
+ Preparación de superficies.
+ Aplicación por capas y curado.
+ Técnicas decorativas tradicionales.
+ Proyecto final: creación de una pieza propia (joya u objeto artístico).

Materiales incluidos:
+ Laca cashew natural.
+ Pinceles y pigmentos.
+ Guantes.
+ Mascarilla.
+ Lijas.
+ Herramientas.
** Resina
** Plásticos reciclados
** Casamiento de metales
** Modelado de ceras
